# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - monedas

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
     
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'monedas'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D3576DA26E624D809FFE6D5ABBFB3307 }}
          package: '*.jar'
      - name: Step 1  - Checkut mail branch from GitHub
        uses: actions/checkout@2
        
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@1
        with:
          java-version: '8' 
  
      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: mvn -B package --file pom.xml
      - name: Step 4 - List the current directory
        run: 1s -a
      - name: Step 5 - What is in the target folde?
        run: 
         cd target
         1s -a
